# Change these first
owner: GiDHome
repo: status-licence-manager

sites:
  - name: Licence Manager
    url: https://licence.gidsimulation.com/
  - name: Licence Manager - Login - API
    method: POST
    url: https://licence.gidsimulation.com/v1/Auth/Login
    headers:
      - "Content-Type: application/json"
      - "Authorization: Basic $LOGIN_BASIC"
    body: '{ "machine_name": "status" }'
  - name: Licence Manager - View list licences
    url: https://licence.gidsimulation.com/View/UserLicence
    headers:
      - "Authorization: Bearer $TOKEN_AUTH"
  - name: Licence Manager - list licences - API
    method: GET
    url: https://licence.gidsimulation.com/v1/UserLicence/List
    headers:
      - "Authorization: Bearer $TOKEN_AUTH"

status-website:
  baseUrl: /status-licence-manager
  logoUrl: https://www.gidhome.com/wordpress/wp-content/uploads/GiDlogo512-150x150.png
  name: GiD Licence Manager Status
  introTitle: "**GiD Licence Manager** status check"
  introMessage: Check if servers are running OK
  navbar:
    - title: Status
      href: /
    - title: Licence Manager
      href: https://licence.gidsimulation.com/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
